# Generated by Django 2.2.24 on 2021-06-16 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('paginas', models.IntegerField()),
                ('publicado', models.BooleanField()),
                ('fecha_publicacion', models.DateTimeField()),
            ],
        ),
    ]
