# Generated by Django 2.2.24 on 2021-06-17 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='edicion',
            field=models.IntegerField(null=True),
        ),
    ]
