# Generated by Django 2.2.24 on 2021-06-17 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0001_initial'),
        ('libros', '0002_libros_edicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='editorial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='editorial.Editorial'),
        ),
    ]
