# Generated by Django 2.2.24 on 2021-06-17 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0001_initial'),
        ('libros', '0003_libros_editorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='autores',
            field=models.ManyToManyField(related_name='libros', to='autor.Autor'),
        ),
    ]
